# Learn about all the available settings - https://docs.openinterpreter.com/settings/all-settings

[llm]
model = "model-supplier/model-name"
context_window = 110000
max_tokens = 4096
temperature = 0.4
api_base = "model-supplier-base-url"
api_key = "YOUR_API_KEY"
supports_functions = false
supports_vision = false

[interpreter]
offline = false
loop = false
auto_run = true
os = false
import_computer_api = false

[custom]
instructions = "Today's date is {today}."
