[minimizer]
api_base ="http://localhost:41251"
api_key = "test-123"
model = "litellm_proxy/claude-3-7-sonnet"
temperature = 0.1
max_retries = 3
retry_delay = 2


[narrator]
api_base ="http://localhost:41251"
api_key = "test-123"
model = "litellm_proxy/claude-3-7-sonnet"
temperature = 0.1
max_retries = 3
retry_delay = 2

[reconstructor]
api_base ="http://localhost:41251"
api_key = "test-123"
model = "litellm_proxy/claude-3-7-sonnet"
temperature = 0.1
max_retries = 3
retry_delay = 2