[minimizer]
api_base ="http://localhost:37842"
api_key = "test-123"
model = "litellm_proxy/claude-3-7-sonnet"
temperature = 0.1
max_retries = 3
retry_delay = 2


[extractor]
api_base ="http://localhost:37842"
api_key = "test-123"
model = "litellm_proxy/claude-3-7-sonnet"
temperature = 0.1
max_retries = 3
retry_delay = 2